### ISSUE TITLE
Issue with Embeddings

### ISSUE THREAD

**Issue by maarek** [BlenderNeko/ComfyUI_Cutoff#2]
ClipRegionBasePrompt does not handle embeddings like ClipTextEncode.

Prompt: `woman, embedding:charturner.pt`

`
File "C:\Users\jerem\ComfyUI\custom_nodes\ComfyUI_Cutoff-master\cutoff.py", line 57, in add_clip_region
    prompt_tokens = np.array([[y[0] for y in x]for x in clip_regions["base_tokens"]])
ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 2 dimensions. The detected shape was (1, 77) + inhomogeneous part.
`

**Comment by BlenderNeko** [comment]
Totally forgot for a moment that textual inversion embeddings existed. They should now behave like first class citizens, i.e. you should be able to use them in CLIPRegionsBasePrompt, and in the region_text and target_text of CLIPSetRegion nodes. Note that when using an embedding as a target_text you still have to escape any underscores in the name.

I have not tested all of this with extremely long embeddings but closing this issue for now
